# Generated by Django 5.2.7 on 2025-12-11 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_municipalityofficial_municipalityotp_delete_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalityofficial",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="official_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
