# Generated by Django 5.2.7 on 2025-12-11 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_municipality_latitude_and_more"),
        ("api", "0003_municipalityofficial_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="municipalityofficial",
            name="email",
        ),
        migrations.RemoveField(
            model_name="municipalityofficial",
            name="name",
        ),
        migrations.RemoveField(
            model_name="municipalityofficial",
            name="password",
        ),
        migrations.AddField(
            model_name="municipalityofficial",
            name="designation",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="municipalityofficial",
            name="municipality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="officials",
                to="account.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="municipalityofficial",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="official_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
