# Generated by Django 5.2.7 on 2025-12-13 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_municipality_latitude_and_more"),
        ("api", "0004_remove_municipalityofficial_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipalityofficial",
            name="designation",
            field=models.CharField(default="Employee", max_length=100),
        ),
        migrations.AlterField(
            model_name="municipalityofficial",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="officials",
                to="account.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="municipalityofficial",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="official_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
