# Generated by Django 5.2.7 on 2026-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_municipality_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="area_sq_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="commissioner_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="establishment_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="mayor_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="wards_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
