# Generated by Django 5.2.7 on 2026-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_municipality_area_sq_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="honesty_score",
            field=models.IntegerField(default=100),
        ),
    ]
