# Generated by Django 5.2.7 on 2025-10-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_latitude_alter_complaint_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
