# Generated by Django 5.2.7 on 2025-10-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_latitude_alter_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
